FROM ruby:3.0.4-alpine

ENV APP_PATH /var/app
ENV BUNDLE_VERSION 2.2.22
ENV BUNDLE_PATH /usr/local/bundle/gems
ENV TMP_PATH /tmp/
ENV RAILS_LOG_TO_STOUT true
ENV RAILS_PORT 3000

COPY ./dev-docker-entrypoint.sh /usr/local/bin/dev-docker-entrypoint.sh
COPY ./test-docker-entrypoint.sh /usr/local/bin/test-docker-entrypoint.sh
RUN chmod +x /usr/local/bin/dev-docker-entrypoint.sh && chmod +x /usr/local/bin/test-docker-entrypoint.sh

# Setup deps for rails
RUN apk -U add --no-cache \
build-base \
git \
postgresql-dev \
postgresql-client \
libxml2-dev \
nodejs \
yarn \
imagemagick \
tzdata \
less \
sqlite-dev \
@@ rm -rf /var/cache/apk/* \
&& mkdir -p $APP_PATH

RUN gem install bundler --version "$BUNDLE_VERSION" \
&& rm -rf $GEM_HOME/cache/*

RUN yarn install --check-files

WORKDIR $APP_PATH

EXPOSE $RAILS_PORT

ENTRYPOINT ["bundle", "exec"]